name: CI/CD prod

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Variables used
        run: |
          echo User:                  ${{ vars.USER }}"
          echo Host:                  ${{ vars.HOST }}"
          echo Remotepath:            ${{ vars.REMOTEPATH }}"
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Build assets
        run: npm run build
      - uses: contention/rsync-deployments@v2.0.0
        with:
          FLAGS: -avzr --delete
          EXCLUDES: --exclude .github
          USER: ${{ vars.USER }}
          HOST: ${{ vars.HOST }}
          LOCALPATH: /
          REMOTEPATH: ${{ vars.REMOTEPATH }}
          DEPLOY_KEY: ${{ vars.DEPLOY_KEY }}
